#!/bin/bash

# Function to get IP address for a subdomain
get_ip() {
    local subdomain=$1
    dig +short "$subdomain.$domain" | tail -n1
}

# Function to print information about a subdomain
print_info() {
    local subdomain=$1
    local ip=$(get_ip "$subdomain")
    echo "The subdomain $subdomain is a A record and points to $ip"
}

# Main script

# Ensure correct number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Assign domain and subdomain variables
domain=$1
subdomain=$2

# If subdomain is not provided, get information for default subdomains
if [ -z "$subdomain" ]; then
    print_info www
    print_info lb-01
    print_info web-01
    print_info web-02
else
    # Get information for specific subdomain
    print_info "$subdomain"
fi

