#!/usr/bin/env bash
# 404 Page custom

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
N_RED="\n\tlocation /redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo cp /etc/nginx/sites-available/default{,.backup}
sudo sed -i "53i $N_RED" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
N_RED404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\n\tlocation = \/404.html {\n\t\root \/var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$N_RED404/" /etc/nginx/sites-available/default

# sudo sed -i '/^\server_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
