#!/usr/bin/env bash
# script to print a string and stop it using kill

# find the process ID (PID) of the 4-to_infinity_and_beyond
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n "$pid" ]]; then
	# echo "Terminating 4-to_infinity_and_beyond process with PID $pid"
	kill "$pid"
else
	echo "4-to_infinity_and_beyond process not found."
fi
