#!/usr/bin/env bash
# This script displays 'To infinity and beyond' with a sleep of 2 seconds
# It reacts to the SIGTERM signal with "I am invincible!!!"

# Set up trap outside the loop
trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

