#!/usr/bin/env bash
# this script displays string and says another on a line

count=0

while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
