#!/usr/bin/env bash
# script to diplay the time using 'while' loop

hour=0
minute=1

while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $minute -le 59 ]; do
		echo "$minute"
		minute=$((minute + 1))
	done
	hour=$((hour + 1))
	minute=1
done
