#!/usr/bin/env bash
# script that checks the school file's existence and provides info

file=school

if [ -e "$file" ]; then
	echo "school file exists"
else
	echo "school file does not exist"
	exit 1
fi
if [ ! -s "$file" ]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi

if [ -f "$file" ]; then
	echo "school is a regular file"
fi
