#!/usr/bin/env bash
# script that configures the container to run Nginx as the nginx user
sudo sed -Ei "s/\s*#?\s*user .*/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/\(listen\s*\)80/\18080/" /etc/nginx/sites-enabled/default
sudo sed -Ei "s/(listen (\[::\]:?80))/\180/" /etc/nginx/sites-enabled/default
sudo service nginx restart
